config/routes.rb
Rails.application.routes.draw do



  # namespace :developers do
    # root to: 'pages#index'
  # end




  require 'sidekiq/web'


  # match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]
  devise_for :admin_users, path: 'admin'
  devise_for :drivers, path: 'driver' ,:controllers => { :sessions => "drivers/sessions", registrations: "drivers/registrations" }

  get "/drivers" => redirect('driver')
  get "/drivers/sign_in" => redirect('driver')
  get "drivers/sign_up" => redirect('driver')

  get "/admin_users" => redirect('admin')
  get "admin_users/sign_in" => redirect('admin')


  namespace :api, :defaults => {:format => 'json'} do
    namespace :v1 do

      namespace :b2b do
        resources :sessions do
          post 'check', on: :collection
        end

        resources :users do
          post 'login', on: :collection
          post 'logout', on: :collection
          post 'change_password', on: :collection
        end
        resources :deliveries
        resources :promocodes
        resources :drivers
        resources :vehicle_types

      end

      namespace :driver do
        resources :sessions do
          post 'check', on: :collection
        end

        resources :drivers do
          post 'login', on: :collection
          post 'logout', on: :collection

          post 'update_location', on: :collection
          post 'change_password', on: :collection
          get 'earnings', on: :collection
          get 'remove_availability', on: :collection
        end
        resources :deliveries do
          post 'changeStatus', on: :collection
          post 'changeDeliveryStatus', on: :collection
          get 'testPush', on: :collection
        end
      end
    end
  end

  namespace :admin do

    root to: 'dashboard#index'
    resources :dashboard
    resources :users do
      collection do
        get 'report'
        get 'deactive'
      end
    end
    resources :drivers do
      collection do
        get 'pending_list'
        get 'suspend_list'
        get 'verify'
        get 'report'
        get 'verified'
        get 'map'

      end

      member do

        end
    end
    resources :vehicles
    resources :offers
    resources :deliveries do
      collection do
        get 'later'
        get 'completed'
        get 'abendand'
      end
      member do
        get 'allocation'
        get 'cancel'
      end
    end

    resources 'reports', only: [:index] do
      collection do
        get "daily_deliveries"
        post "daily_deliveries"
      end
    end

    resources :admin_notifications

  end

  resources :driver do
    collection do
      get 'personal_info'
      post 'personal_info'
      get 'employment_info'
      post 'employment_info'
      get 'health'
      post 'health'
      get 'rehabilitation'
      post 'rehabilitation'
      get 'verification'
      post 'verification'
      get 'driving_license'
      post 'driving_license'
      get 'references'
      post 'references'
      get 'supporting_documents'
      post 'supporting_documents'
      get 'declaration_consent'
      post 'declaration_consent'
      get 'equal_opportunities'
      post 'equal_opportunities'
      get 'confirmation'
      post 'confirmation'

      get 'terms'
    end
  end


  #resources :notifications


  root to: 'driver#index'

  mount Sidekiq::Web => '/sidekiq'

end

app/controllers/admin/drivers_controller.rb
class Admin::DriversController < AdminController

  def index
    if params[:q].nil? || params[:q].empty?
      @drivers  = Driver.paginate(:page => params[:page], :per_page => 20).where('status = 1 AND is_delete = 0').order("created_at DESC")
    else
    
    
        if params[:option] == "id"
            
            @drivers  = Driver
            .joins(:delivery_vehicle)
            .paginate(:page => params[:page], :per_page => 20)
            .where("drivers.id = ?","#{params[:q]}")
            .order("created_at DESC")
            
        elsif params[:option] == "name"
        
            @drivers  = Driver
            .joins(:delivery_vehicle)
            .paginate(:page => params[:page], :per_page => 20)
            .where('drivers.first_name LIKE (?) OR drivers.middle_name LIKE (?) OR drivers.surname LIKE (?)',"%#{params[:q]}%","%#{params[:q]}%","%#{params[:q]}%")
            .order("created_at DESC")
        
        elsif params[:option] == "email"
        
            @drivers  = Driver
            .joins(:delivery_vehicle)
            .paginate(:page => params[:page], :per_page => 20)
            .where('drivers.email = ?',"#{params[:q]}")
            .order("created_at DESC")
            

        elsif params[:option] == "vehicle"

            @drivers  = Driver
            .joins(:delivery_vehicle)
            .paginate(:page => params[:page], :per_page => 20)
            .where('delivery_vehicles.name LIKE (?)', "%#{params[:q]}%")
            .order("created_at DESC")
            
        end



    end
  end



  def map
    @allAvailableDrivers = DriverLocation.allDrivers()
    @hash = Gmaps4rails.build_markers(@allAvailableDrivers) do |userLocation, marker|
      marker.lat userLocation.lat
      marker.lng userLocation.lon
      marker.picture({
        'url'   => view_context.image_url(userLocation.driver_status_id == 1 ? 'availableDriver.png' :'unavailableDriver.png'),
        'width' => 50,
        'height'=> 50
         })
      marker.infowindow  render_to_string( partial: 'marker_info', locals: { userLocation: userLocation})
    end
  end





  def pending_list
    if params[:keyword].nil? || params[:keyword].empty?
      @drivers  = Driver.paginate(:page => params[:page], :per_page => 20).where('status = 0').order("created_at DESC")
    else
      @drivers  = Driver.paginate(:page => params[:page], :per_page => 20).where('status = 0 AND (first_name LIKE (?) OR middle_name LIKE (?) OR surname LIKE (?) OR email LIKE (?))',"%#{params[:keyword]}%","%#{params[:keyword]}%","%#{params[:keyword]}%","%#{params[:keyword]}%").order("created_at DESC")
    end
  end


  def suspend_list
    if params[:keyword].nil? || params[:keyword].empty?
      @drivers  = Driver.paginate(:page => params[:page], :per_page => 20).where('is_delete = 1').order("created_at DESC")
    else
      @drivers  = Driver.paginate(:page => params[:page], :per_page => 20).where('is_delete = 1 AND (first_name LIKE (?) OR middle_name LIKE (?) OR surname LIKE (?) OR email LIKE (?))',"%#{params[:keyword]}%","%#{params[:keyword]}%","%#{params[:keyword]}%","%#{params[:keyword]}%").order("created_at DESC")
    end
  end

  def verify
    @driver = Driver.find(params[:id])
    @driver.status = 1
    @driver.save

    redirect_to pending_list_admin_drivers_path
  end

  def report
    @driver = Driver.find(params[:driver_id])
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "report"
      end
    end
  end

  def edit
    @driver = Driver.find(params[:id])
  end

  def show
    @driver = Driver.find(params[:id])
  end

  def update
    @driver = Driver.find(params[:id])

    if @driver.update(driver_params)
      redirect_to admin_drivers_path
    else
      render :template => 'admin/drivers/edit'
    end

  end

  def driver_params
    params.require(:driver).permit(:is_delete)

  end
end

app/controllers/api/v1/admin/drivers_controller.rb
class Api::V1::Admin::DriversController < ApplicationController

  before_filter :set_driver, only: [:show, :update]

  def index
    @drivers = Driver.all
    render :json => @drivers
  end

  def show
    render :json => @driver
  end

  def create
  end

  def update
  end


  private
    def set_driver
      @driver = Driver.find(params[:id])
    end

    def delivery_params
      params.require(:driver).permit(:name, :start_date, :end_date, :description, :status)
    end

end

app/controllers/api/v1/b2b/drivers_controller.rb
class Api::V1::B2b::DriversController < UserApiController

  before_action :set_driver, only: [:show]

  api :GET, '/v1/b2b/drivers/', 'Fetch all drivers in the system'
  formats ['json']
  description <<-EOS
      == Long description
       Get the list of deliveries related to your account as
       identified by the X-Auth-Token
    EOS
  def index
    allAvailableDrivers = []

    if params[:allDrivers]
      DriverLocation.allDrivers().each do |driver_allocation|
        allAvailableDrivers << driver_allocation.as_json(:include => {driver: {
          :methods => [:avatar_url, :lat, :lon], only: [:first_name, :surname,:middle_name , :mobile_no, :land_no]}
        })
      end
    elsif params[:vehicle_type_id]
      DriverLocation.allDrivers.drivers_by_vehicle_type(params[:vehicle_type_id]).each do |driver_allocation|
        allAvailableDrivers << driver_allocation.as_json(:include => {driver: {
          :methods => [:avatar_url, :lat, :lon], only: [:first_name, :surname, :middle_name, :mobile_no, :land_no]}
        })
      end
    else
      DriverLocation.allAvailableDrivers().each do |driver_allocation|
        allAvailableDrivers << driver_allocation.as_json(:include => {driver: {
          :methods => [:avatar_url, :lat, :lon], only: [:first_name, :surname, :middle_name, :mobile_no, :land_no]}
        })
      end
    end

    render :json => {:success => :true , :drivers => allAvailableDrivers}
  end

  def show
    if @driver
      render :json => {:success => :true , :driver => @driver.as_json(:methods => [:avatar_url, :lat, :lon], :only => [:first_name, :surname, :middle_name, :mobile_no, :land_no])}
    else
      render :json => {:success => :false , :errors => ['You dont have driver details']}, status: 404
    end
  end

  private

    def set_driver
      @driver = Driver.find(params[:id])
    end
end

app/controllers/api/v1/driver/drivers_controller.rb
class Api::V1::Driver::DriversController < DriverApiController

  before_filter :authenticate, :except => [:login]

  def login
    driver = Driver.login(params[:email], params[:password])
    if driver.present?

      if driver[0].status == true

        if driver[0].is_delete == 1
          render :json => {:success => :false, :errors => ['Your account has been suspended']}
        else
          if params[:push_token] && params[:device_type]
            driver[0].updateDriverDevice(params[:push_token], params[:device_type])
            driver[0].new_token!
          end
          #driver[0].manualAllocation
          #Delivery.re_allocate
          render :json => {:success => :true , :driver => driver[0].as_json(:methods => [:avatar_url])}
        end
      else
        render :json => {:success => :false, :errors => ['Your account has not been approved yet']}
      end
      
    else
      render :json => {:success => :false, :errors => ['Email password combination invalid']}
    end
  end

  def update_location

    if params[:lat] && params[:lon]
      @driver_locations = DriverLocation.find_by_driver_id(@current_user.id)
      @driver_location = DriverLocation.new()
      @driver_location.driver_status_id = 1
      if @driver_locations
        @driver_location = @driver_locations
      else
        #Delivery.re_allocate
      end

      @driver_location.driver_id  = @current_user.id
      @driver_location.lat        = params[:lat]
      @driver_location.lon        = params[:lon]
      @driver_location.save

      Delivery.resetAllocations()

      current_user.manualAllocation
      Delivery.re_allocate

      render :json => {:success => :true , :message => 'updated successfully'}
    else
      render :json => {:success => :false , :errors => ['field(s) are blank']}
    end
    Rails.logger.debug "DRIVER #{@current_user.id}"

  end

  def show
    if @current_user
      render :json => {:success => :true , :driver => @current_user.as_json(:methods => [:avatar_url])}
    else
      render :json => {:success => :false , :errors => ['You dont have driver details']}
    end
  end

  def update
    if @current_user.update(driver_update_params)

      render :json => {:success => :true , :driver => @current_user.as_json(:methods => [:avatar_url])}

      Rails.logger.info("LAHIRU IS TRYING TO UPDATE #{@current_user}")

    else
      render :json => {:success => :false , :errors => @current_user.errors.full_messages}
    end
  end

  def change_password
    if params[:password] && params[:confirm_password] && params[:old_password]
      if params[:password] == params[:confirm_password]

        if @current_user.session_token == Digest::SHA1.hexdigest(params[:old_password])
          @current_user.updatePassword(params[:password])
          render :json => {:success => :true , :user =>  @current_user.as_json(:methods => [:avatar_url])}
        else
          render :json => {:success => :false , :errors => ['old password does not match']}
        end
      else
        render :json => {:success => :false , :errors => ['password does not match']}
      end
    else
      render :json => {:success => :false , :errors => ['field are blanks']}
    end
  end

  def logout
    if params[:push_token] && params[:device_type]
      current_user.removeDevices(params[:push_token], params[:device_type])
      current_user.removeLocations
      render :json => {:success => :true , :message => 'log out'}
    else
      render :json => {:success => :false , :errors => ['field are blanks']}
    end
  end

  def earnings
    render :json => {:success => :true , :totalCostMonthly => current_user.getTotalCostForCompletedDeliveriesMonthly, :commissionMonthly => current_user.getCommissionMonthly, :totalCostToday => current_user.getTotalCostForCompletedDeliveriesToday, :commissionToday => current_user.getCommissionToday, :deliveryCountMonthly => current_user.getTotalCostForCompletedDeliveryCountMonthly, :deliveryCountToday => current_user.getTotalCostForCompletedDeliveryCountToday}
  end

  def remove_availability
    if params[:availability] == '1'
      current_user.goOnline
    else
      current_user.goOffline
    end
    render :json => {:success => :true , :message => 'availability changed'}
  end

  def driver_update_params
    params.require(:driver).permit(:first_name, :date_of_birth, :gender, :mobile_no,:surname, :middle_name, :avatar,  :country_code)
  end
end

app/controllers/api/v1/driver/sessions_controller.rb
class Api::V1::Driver::SessionsController < DriverApiController
  before_filter :authenticate, :except => [:check]

  #
  # Check where user exist
  #
  def check

    if (token = request.headers['X-Auth-Token'])
      if (current_user = Driver.find_by_token(token))
        @current_user = current_user

        if params[:push_token] && params[:device_type]
          @current_user[0].updateUserHandset(params[:push_token], params[:device_type])
        end
        @current_user.set_time_zone_to_driver(params[:timezone])

        render :json => {:success => :true , :user => @current_user.as_json(:methods => [:avatar_url])}
      else
        render :nothing => true, :status => 401, :json => {:success => :false }
      end
    else
      render :nothing => true, :status => 403, :json => {:success => :false }
    end
  end

end

app/controllers/drivers/registrations_controller.rb
class Drivers::RegistrationsController < Devise::RegistrationsController

  before_filter :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    # devise_parameter_sanitizer.for(:sign_up).push(:email, :password, :password_confirmation, :title, :first_name, :surname,
    #                                  :middle_name, :mobile_no, :land_no, :gender, :delivery_vehicle_id)

    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation, :title, :first_name, :surname,
                                                       :middle_name, :mobile_no, :land_no, :gender, :delivery_vehicle_id])

  end


  # def sign_up_param
  #   params.require(:driver).permit(:email, :password, :password_confirmation, :title, :first_name, :surname,
  #                                :middle_name, :mobile_no, :land_no, :gender, :delivery_vehicle_id)
  # end

end

app/controllers/drivers/sessions_controller.rb
class Drivers::SessionsController < Devise::SessionsController
    respond_to :json
end

app/helpers/admin/drivers_helper.rb
module Admin::DriversHelper
end

app/helpers/api/v1/admin/drivers_helper.rb
module Api::V1::Admin::DriversHelper
end

app/helpers/api/v1/driver/sessions_helper.rb
module Api::V1::Driver::SessionsHelper
end

app/helpers/driver_helper.rb
module DriverHelper
end

app/views/driver/confirmation.html.erb
<%= form_for @driver, url: confirmation_driver_index_path , :method => 'POST' , :html => {:class => 'form'}  do |f| %>

	<!-- Main content -->
	<section class="content content-bg">
		<div class="row">
			<div class="col-lg-12 col-xs-12">
				<h3 class="instruction">
					THE INFORMATION IN THIS FORM WILL BE TREATED IN STRICTEST CONFIDENTIALITY IN ACCORDANCE WITH THE 1998 DATA PROTECTION ACT.
				</h3>
						
				<p class="instruction">
					Due to the high security of some of iWAD Customers, you are required to supply personal details to enable security checks to be carried out where appropriate. Please ensure all sections of this application form are completed and there are no gaps.
				</p>
			</div><!-- ./col -->
		</div><!-- /.row -->
		<br />
		<% if @driver && @driver.errors && @driver.errors.count > 0 %>
			<div class="row">
				<div class="col-xs-12">
					<div class="alert alert-error alert-block" role="alert">
						<ul class="errorMessageList">
							<% @driver.errors.full_messages.each do |error| %>
								<li><%= error %></li>
							<% end %>
						</ul>
					</div>
				</div>
			</div>
		<% end %>
		<div class="row">
			<div class="col-lg-11 col-xs-12">
				<div class="form-group">
					<label class="control-label col-lg-12 col-xs-12" for="posaware">How did you hear about this position :</label>
								
					<div class="col-lg-10 col-xs-12">
						<%= f.text_area :abt_position, autofocus: true, class:'form-control',  :placeholder => 'Enter how you came to know of this position', :rows => '3' %>
					</div>
				</div>
			</div><!-- ./col -->
		</div><!-- /.row -->
		<br />
					
		<div class="row">
			<div class="col-lg-11 col-xs-12">
				<div class="form-group">
					<div class="col-lg-12 col-xs-12">
						<label class="checkbox-inline"><input type="checkbox" value="">I hereby agree that all details added in this application process are true to the best of my knowledge and up to date.</label>
					</div>
				</div>
			</div><!-- ./col -->
		</div><!-- /.row -->
		<br />
				
		<div class="row">
			<div class="col-lg-6 col-xs-12"></div>
			<div class="col-lg-6 col-xs-12">
				<div class="col-lg-8 col-xs-12"></div>
				<div class="col-lg-2 col-xs-12">
					<button type="submit" class="btn btn-success">Complete &nbsp;&nbsp;<i class="glyphicon glyphicon-ok"></i></button>
				</div><!-- ./col -->
			</div>
		</div><!-- /.row -->
	</section>
<% end %>

app/views/driver/declaration_consent.html.erb
<%= form_for @driver, url: declaration_consent_driver_index_path , :method => 'POST' , :html => {:class => 'form'}  do |f| %>
	<!-- Main content -->
	<% if @driver && @driver.errors && @driver.errors.count > 0 %>
		<div class="row">
			<div class="col-xs-12">
				<div class="alert alert-error alert-block" role="alert">
					<ul class="errorMessageList">
						<% @driver.errors.full_messages.each do |error| %>
							<li><%= error %></li>
						<% end %>
					</ul>
				</div>
			</div>
		</div>
	<% end %>
	<section class="content content-bg">
		<div class="row">
			<div class="col-lg-12 col-xs-12">
				<h3 class="instruction">
					THE INFORMATION IN THIS FORM WILL BE TREATED IN STRICTEST CONFIDENTIALITY IN ACCORDANCE WITH THE 1998 DATA PROTECTION ACT.
				</h3>
						
				<p class="instruction">
					Due to the high security of some of iWAD Customers, you are required to supply personal details to enable security checks to be carried out where appropriate. Please ensure all sections of this application form are completed and there are no gaps.
				</p>
			</div><!-- ./col -->
		</div><!-- /.row -->
		<br />
			
		<div class="row">
			<div class="col-lg-11 col-xs-12">
				<div class="form-group">
					<p class="col-lg-12 col-xs-12">The information contained within this application form will be veirfied by iWAD using a pre-employment 
						screening specialist. We will handle your data in accordance with the requirements of the Data Protection Act 1998 and any relevant local legislation. 
						iWAD will only use your personal data for the purpose of pre-employment screening.</p>
				</div>
			</div><!-- ./col -->
		</div><!-- /.row -->
		<br />
					
		<div class="row">
			<div class="col-lg-11 col-xs-12">
				<div class="form-group">
					<p class="col-lg-12 col-xs-12">I understand and agree that my appointment is conditional upon the verification to iWAD, provided on the form and that 
						this information and that contained on attached documents is true and completed to the best of my knowledge.</p>
				</div>
			</div><!-- ./col -->
		</div><!-- /.row -->
		<br />
					
		<div class="row">
			<div class="col-lg-11 col-xs-12">
				<div class="form-group">
					<p class="col-lg-12 col-xs-12">I also understand that I may incur civil and/or criminal liability if I attempt to obtain an appointment by deception 
						and that any misrepresentation, omission of a material fact or deception will be the cause for immediate cancellation of consideration for 
						employment/appointment, or for dismissal if already employed/appointed.</p>
				</div>
			</div><!-- ./col -->
		</div><!-- /.row -->
		<br />
					
		<div class="row">
			<div class="col-lg-11 col-xs-12">
				<div class="form-group">
					<p class="col-lg-12 col-xs-12">I hereby authorise iWAD to verify information presented on this formand to the extent permitted by law, to procure 
						investigative and credit history reports for that purpose in the UK, and if appropriate, overseas.</p>
				</div>
			</div><!-- ./col -->
		</div><!-- /.row -->
		<br />
					
		<div class="row">
			<div class="col-lg-11 col-xs-12">
				<div class="form-group">
					<p class="col-lg-12 col-xs-12">I also voluntarily authorise iWAD to perform reference checks of my employment/assignment history, including my current 
						employment/assignment. I understand that no contact will be made with my current employer/agency until I have either resigned my employment with them 
						or agreed to the contact in advance of this.</p>
				</div>
			</div><!-- ./col -->
		</div><!-- /.row -->
		<br />
					
		<div class="row">
			<div class="col-lg-11 col-xs-12">
				<div class="form-group">
					<p class="col-lg-12 col-xs-12">I am aware that it may be necessary, if I have lived or worked outside the European Union, for the information given in 
						this application to be tranferred to countries outside of the European Union. I understand that this would only be for the purpose of verification, and 
						that some countries have less comprehensive data protection legislation than those in the European Union.</p>
				</div>
			</div><!-- ./col -->
		</div><!-- /.row -->
		<br />
					
		<div class="row">
			<div class="col-lg-11 col-xs-12">
				<div class="form-group">
					<p class="col-lg-12 col-xs-12">I hereby authorise iWAD to check details with/against fraud prevention databases. Should our investigations identify fraud 
						or the commission of any other criminal offence by you <a href="#">on your part</a> when applying for, or during the course of your duties with iWAD, we 
						will record details of this on the fraud prevention databases. This information may be accessed from the UK and other countries, and used by law 
						enforcement agencies and by us and other organisations to prevent fraud. Please sign below to confirm that you understand how your data will be used 
						should our investigations identify fraud or the commission of any other criminal offence by you.</p>
				</div>
			</div><!-- ./col -->
		</div><!-- /.row -->
		<br />
					
		<div class="row">
			<div class="col-lg-11 col-xs-12">
				<div class="form-group">
					<p class="col-lg-12 col-xs-12">I authorise iWAD to apply for a disclosure of criminal convictions on my behalf and I agree to provide any assistance or 
						documentation required to complete the Disclosure application. I consent to the information contained in the Disclosure being viewed by iWAD. I understand 
						that iWAD will treat the Disclosure in accrodance with their policy on the secure storage, handling, use, retention and disclosure of Disclosure information.</p>
				</div>
			</div><!-- ./col -->
		</div><!-- /.row -->
		<br />
					
		<div class="row">
			<div class="col-lg-11 col-xs-12">
				<div class="form-group">
					<div class="col-lg-12 col-xs-12">
						<label class="checkbox-inline"><%= f.check_box :declaration_agreement %>I hereby agree that I have read the above declaration and consent.</label>
					</div>
				</div>
			</div><!-- ./col -->
		</div><!-- /.row -->
		<br />
				
		<div class="row">
			<div class="col-lg-6 col-xs-12"></div>
			<div class="col-lg-6 col-xs-12">
				<div class="col-lg-8 col-xs-12"></div>
				<div class="col-lg-2 col-xs-12">
					<button type="submit" class="btn btn-success">Proceed &nbsp;&nbsp;<i class="glyphicon glyphicon-arrow-right"></i></button>
				</div><!-- ./col -->
			</div>
		</div><!-- /.row -->
	</section>
<% end %>

app/views/driver/driving_license.html.erb
<%= form_for @driver, url: driving_license_driver_index_path , :method => 'POST' , :html => {:class => 'form'}  do |field| %>
	<!-- Main content -->
	<section class="content content-bg">
		<div class="row">
			<div class="col-lg-12 col-xs-12">
				<h3 class="instruction">
					THE INFORMATION IN THIS FORM WILL BE TREATED IN STRICTEST CONFIDENTIALITY IN ACCORDANCE WITH THE 1998 DATA PROTECTION ACT.
				</h3>
						
				<p class="instruction">
					Due to the high security of some of iWAD Customers, you are required to supply personal details to enable security checks to be carried out where appropriate. Please ensure all sections of this application form are completed and there are no gaps.
				</p>
			</div><!-- ./col -->
		</div><!-- /.row -->
		<br />
		<% if @driver && @driver.errors && @driver.errors.count > 0 %>
			<div class="row">
				<div class="col-xs-12">
					<div class="alert alert-error alert-block" role="alert">
						<ul class="errorMessageList">
							<% @driver.errors.full_messages.each do |error| %>
								<li><%= error %></li>
							<% end %>
						</ul>
					</div>
				</div>
			</div>
		<% end %>
		<div class="row">
			<div class="col-lg-12 col-xs-12">
				<div class="form-group">
					<label class="col-lg-7 col-xs-12">Do you hold a full license valid in the UK?</label>
								
					<div class="col-lg-5 col-xs-12">
						<label class="radio-inline"><%= radio_button('driver','is_license_valid_in_uk', '1') %>Yes</label>
						<label class="radio-inline"><%= radio_button('driver','is_license_valid_in_uk', '0') %>No</label>
					</div>
				</div>
			</div><!-- ./col -->
		</div><!-- /.row -->
		<br />
				
		<div class="row">
			<div class="col-lg-6 col-xs-12">
				<div class="form-group">
					<label class="control-label col-lg-3 col-xs-12" for="empaddr">Driving License Number</label>
								
					<div class=" col-lg-7 col-xs-12">
						<%= field.text_field :license_no, autofocus: true , class: 'form-control', placeholder:'Enter driving license number' %>
					</div>
				</div>
			</div><!-- ./col -->
		</div><!-- /.row -->
		<br />
				
		<div class="row">
			<div class="col-lg-12 col-xs-12">
				<div class="form-group">
					<label class="col-lg-7 col-xs-12">Are there any endorsements on your license?</label>
								
					<div class="col-lg-5 col-xs-12">
						<label class="radio-inline"><%= radio_button('driver','is_endorsements_on_license', '1') %>Yes</label>
						<label class="radio-inline"><%= radio_button('driver','is_endorsements_on_license', '0') %>No</label>
					</div>
				</div>
			</div><!-- ./col -->
		</div><!-- /.row -->
		<br />
					
		<div class="row">
			<div class="col-lg-12 col-xs-12">
				<div class="form-group">
					<label class="col-lg-7 col-xs-12">Have you had any blameworthy accidents in the last 3 years?</label>
								
					<div class="col-lg-5 col-xs-12">
						<label class="radio-inline"><%= radio_button('driver','is_blameworthy_accidents', '1') %>Yes</label>
						<label class="radio-inline"><%= radio_button('driver','is_blameworthy_accidents', '0') %>No</label>
					</div>
				</div>
			</div><!-- ./col -->
		</div><!-- /.row -->
		<br />
				
		<div class="row">
			<div class="col-lg-12 col-xs-12">
				<div class="form-group">
					<label class="control-label col-lg-12 col-xs-12" for="accidentdet">If yes, please provide details :</label>
								
					<div class=" col-lg-8 col-xs-12">
						<%= field.text_area :blameworthy_accident_info, autofocus: true , class: 'form-control', placeholder:'Enter details' %>

					</div>
				</div>
			</div><!-- ./col -->
		</div><!-- /.row -->
		<br />
					
		<div class="row">
			<div class="col-lg-6 col-xs-12"></div>
			<div class="col-lg-6 col-xs-12">
				<div class="col-lg-8 col-xs-12"></div>
				<div class="col-lg-2 col-xs-12">
					<button type="submit" class="btn btn-success">Proceed &nbsp;&nbsp;<i class="glyphicon glyphicon-arrow-right"></i></button>
				</div><!-- ./col -->
			</div>
		</div><!-- /.row -->
	</section>
<% end %>

app/views/driver/index.html.erb
    <div class="row">
        <div class="col-xs-12">
            <div class="alert alert-success alert-block" role="alert">
                <ul class="errorMessageList">
                        <li style="list-style:none;font-size:32px;font-weight:500;">Successfully Added <br/>
                            <span style="font-size:14px;color:#fff;">The iWAD admin will be reviewing your registration details. We will get back to you within 48 hours with a response to your registered mail account.</span>
                        </li>
                </ul>
            </div>
        </div>
    </div>

<!--<a data-method="delete" href="<%= destroy_driver_session_path %>"><i class="fa fa-laptop"></i> Log Out </a> -->