config/routes.rb
Rails.application.routes.draw do



  # namespace :developers do
    # root to: 'pages#index'
  # end




  require 'sidekiq/web'


  # match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]
  devise_for :admin_users, path: 'admin'
  devise_for :drivers, path: 'driver' ,:controllers => { :sessions => "drivers/sessions", registrations: "drivers/registrations" }

  get "/drivers" => redirect('driver')
  get "/drivers/sign_in" => redirect('driver')
  get "drivers/sign_up" => redirect('driver')

  get "/admin_users" => redirect('admin')
  get "admin_users/sign_in" => redirect('admin')


  namespace :api, :defaults => {:format => 'json'} do
    namespace :v1 do

      namespace :b2b do
        resources :sessions do
          post 'check', on: :collection
        end

        resources :users do
          post 'login', on: :collection
          post 'logout', on: :collection
          post 'change_password', on: :collection
        end
        resources :deliveries
        resources :promocodes
        resources :drivers
        resources :vehicle_types

      end

      namespace :driver do
        resources :sessions do
          post 'check', on: :collection
        end

        resources :drivers do
          post 'login', on: :collection
          post 'logout', on: :collection

          post 'update_location', on: :collection
          post 'change_password', on: :collection
          get 'earnings', on: :collection
          get 'remove_availability', on: :collection
        end
        resources :deliveries do
          post 'changeStatus', on: :collection
          post 'changeDeliveryStatus', on: :collection
          get 'testPush', on: :collection
        end
      end
    end
  end

  namespace :admin do

    root to: 'dashboard#index'
    resources :dashboard
    resources :users do
      collection do
        get 'report'
        get 'deactive'
      end
    end
    resources :drivers do
      collection do
        get 'pending_list'
        get 'suspend_list'
        get 'verify'
        get 'report'
        get 'verified'
        get 'map'

      end

      member do

        end
    end
    resources :vehicles
    resources :offers
    resources :deliveries do
      collection do
        get 'later'
        get 'completed'
        get 'abendand'
      end
      member do
        get 'allocation'
        get 'cancel'
      end
    end

    resources 'reports', only: [:index] do
      collection do
        get "daily_deliveries"
        post "daily_deliveries"
      end
    end

    resources :admin_notifications

  end

  resources :driver do
    collection do
      get 'personal_info'
      post 'personal_info'
      get 'employment_info'
      post 'employment_info'
      get 'health'
      post 'health'
      get 'rehabilitation'
      post 'rehabilitation'
      get 'verification'
      post 'verification'
      get 'driving_license'
      post 'driving_license'
      get 'references'
      post 'references'
      get 'supporting_documents'
      post 'supporting_documents'
      get 'declaration_consent'
      post 'declaration_consent'
      get 'equal_opportunities'
      post 'equal_opportunities'
      get 'confirmation'
      post 'confirmation'

      get 'terms'
    end
  end


  #resources :notifications


  root to: 'driver#index'

  mount Sidekiq::Web => '/sidekiq'

end

app/models/user.rb
class User < ActiveRecord::Base
  before_create :account_create_session_token
  before_save :ensure_authentication_token



  VALID_EMAIL_REGEX = /[\w+\-.]+@[a-z\d\-.]+\.[a-z]+/i
  validates :email,                 presence: true, on: :create, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  # validates :date_of_birth,         presence: true, on: :update
  validates :password,              length: {minimum: 6}, on: :create
  validates :country_code, presence: true

  # validates :phone_no, phone: true, on: :create

  # validates :gender     
  # validates :organisation_name
  # validates_uniqueness_of :token

  has_attached_file :avatar,
                    :styles => { :thumb => "400x400#"},
                    :default_url => ":rails_root/public/assets/users/avatar/missing/:style/profile.png",
                    :path => ":rails_root/public/assets/users/avatar/:id/:style/:basename.:extension",
                    :url => "/assets/users/avatar/:id/:style/:basename.:extension"

  validates_attachment :avatar,
                       :content_type => { :content_type => ["image/png", "image/jpg", "image/jpeg"] },
                       :size => { :in => 0..20.megabytes }


  scope :authenticate, ->(email) {
    where('email = :email',
          email: email).limit(1)
  }

  scope :auth_token, -> (token) {
    where('token = :token',
          token: token).limit(1)
  }

  scope :login, ->(email, password) {
    where('email = :email AND password= :password',
          email: email, password: Digest::SHA1.hexdigest(password)).limit(1)
  }



  def account_create_session_token
    # self.token = User.encrypt_sha2(self.email)
    self.password =  Digest::SHA1.hexdigest(self.password)
  end


  def self.encrypt_sha2(text)
    Digest::SHA2.hexdigest text
  end

  def updatePassword(password)
    self.password =  Digest::SHA1.hexdigest(password)
  end

  def getJSON(options = {})
    obj = {
      user_id: self.id,
      name: self.name,
      email: self.email,
      date_of_birth: self.date_of_birth,
      gender: self.gender,
      phone: self.phone_no,
      token: self.token,
    }
    return obj
  end

  def updateUserHandset(token, type)

    handsets = UserDevice.where('user_id =? AND device_type=?', self.id, type)

    if handsets.length == 0
      handset                   =  UserDevice.new()
      handset.token             = token
      handset.device_type       = type
      handset.user_id           = self.id
      handset.save
      Rails.logger.info("CREATING DEVICE TOKEN FOR #{ self.id }")
    else
      Rails.logger.info("UPDATING DEVICE TOKEN FOR #{ self.id }")
      handset = handsets[0]
      handset.user_id           = self.id
      handset.token             = token
      handset.save
    end
  end

  def removeDevices(token, type)
    UserDevice.destroy_all(:token => token , :device_type => type, user_id: self.id)
  end

  def removeSessions(type)
    UserDevice.destroy_all(:device_type => type, user_id: self.id)
  end

  def avatar_url
    return "http://local.iwadbackoffice.com#{self.avatar.url(:thumb)}"
  end

  def completedDeliveries
    return Delivery.where('user_id=? AND delivery_status_id=5', self.id)
  end

  def getTotalCostForCompletedDeliveries
    return self.completedDeliveries.sum(:cost)
  end

  def getCommission
    return (self.getTotalCostForCompletedDeliveries * 80/ 100)
  end

  def decreaseCount
    if self.prepaid_credit_count > 0
      # self.prepaid_credit_count = prepaid_credit_count - 1
      # self.save!

      redeemed = self.prepaid_credit_count - 1
      sql = "UPDATE users SET prepaid_credit_count=#{redeemed} WHERE id= #{self.id}"
      ActiveRecord::Base.connection.execute(sql)
    end
  end



  # @Todo Please use active record method
  # Due to some issue Update isn't working
  def set_prepaid_credits(credits)
    sql = "UPDATE users SET prepaid_credit_count= #{credits} WHERE id= #{self.id}"
    ActiveRecord::Base.connection.execute(sql)
    # self.update_attributes(prepaid_credit_count:  credits)
  end


  # Set time_zone field based on user input
  def set_time_zone_to_user(time_zone)
    if time_zone.nil?
      self.update_attributes(time_zone:  "Europe/London")
    else
      self.update_attributes(time_zone:  time_zone)
    end
  end





  def ensure_authentication_token
    self.token ||= new_token!
  end

  def new_token!
    SecureRandom.hex(36).tap do |random_token|
      update_attributes token: random_token

      # sql = "UPDATE users SET token= #{random_token} WHERE id= #{self.id}"
      # ActiveRecord::Base.connection.execute(sql)

      Rails.logger.info("Set new token for user #{ id }")
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController

  before_action :set_user, only: [:show, :edit, :update, :report]

  def index
    if params[:q].nil? || params[:q].empty?
      @users  = User.paginate(:page => params[:page], :per_page => 20).where(:status => 1)
      .order("created_at DESC")

    else
    
        if params[:option] == "id"
        
            @users  = User.paginate(:page => params[:page], :per_page => 20).where('id = ?',"#{params[:q]}")
            .order("created_at DESC")

        elsif params[:option] == "name"

            @users  = User.paginate(:page => params[:page], :per_page => 20).where('name LIKE ?',"%#{params[:q]}%")
            .order("created_at DESC")

        elsif params[:option] == "email"

            @users  = User.paginate(:page => params[:page], :per_page => 20).where('email = ?',"#{params[:q]}")
            .order("created_at DESC")


        elsif params[:option] == "org"
        
            @users  = User.paginate(:page => params[:page], :per_page => 20).where('organisation_name LIKE ?',"%#{params[:q]}%")
            .order("created_at DESC")
        
        end
      
    end
  end

  def show
  end

  def edit
  end

  def deactive
    if params[:keyword].nil? || params[:keyword].empty?
      @users  = User.paginate(:page => params[:page], :per_page => 20).where(:status => 0).order("created_at DESC")

    else
      @users  = User.paginate(:page => params[:page], :per_page => 20).where('(status = 0 AND organisation_name LIKE (?) OR name LIKE (?) OR email LIKE (?))',"%#{params[:keyword]}%","%#{params[:keyword]}%","%#{params[:keyword]}%").order("created_at DESC")
    end
  end

  def update
    if params[:generate]
      redirect_to report_admin_users_path(format: :pdf, :user_id => params[:id], :target => "_blank")
    else
      # logger.debug "ADMIN UPDATE ACTION FOR USER #{@user}"
      # Rails.logger.info(@user.errors.messages.inspect)

      # @user.set_prepaid_credits(params[:user][:prepaid_credit_count])

      @user.update(user_params)
      logger.debug "ADMIN UPDATE ACTION"


      redirect_to action: 'index'
    end
  end

  def report
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "report"
      end
    end
  end


  protected
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:prepaid_credit_count, :status)
    end
end

app/controllers/api/v1/admin/users_controller.rb
class Api::V1::Admin::UsersController < ApplicationController




  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:prepaid_credit_count)
    end
end

app/controllers/api/v1/b2b/users_controller.rb
class Api::V1::B2b::UsersController < UserApiController
  before_filter :authenticate, :except => [:create, :login]


  def login
    user = User.login(params[:email], params[:password])
    if user.length == 0
      render :json => {:success => :false, :errors => ['Email password combination invalid']}, status: 422
    else
      if params[:push_token] && params[:device_type]
        user[0].updateUserHandset(params[:push_token], params[:device_type])
        user[0].set_time_zone_to_user(params[:time_zone])
        # user[0].new_token!
      end
      render :json => {:success => :true , :user => user[0].as_json(:methods => [:avatar_url])}
    end
  end


  def create
    exUser = User.authenticate(params[:email])
    if exUser.length == 0
      user = User.new(user_params)
      user.status = 1
      if user.save
        if params[:push_token] && params[:device_type]
          user[0].updateUserHandset(params[:push_token], params[:device_type])
          # user[0].new_token!
        end
        render :json => {:success => :true , :user => user.as_json(:methods => [:avatar_url])}, status: 200
      else
        render :json => {:success => :false , :errors => user.errors.full_messages}, status: 422
      end
    else
      render :json => {:success => :false , :errors => ['Email already exits']}, status: 422
    end
  end

  def logout
    if params[:push_token] && params[:device_type]
      current_user.removeDevices(params[:push_token], params[:device_type])
      render :json => {:success => :true , :message => 'log out'}
    else
      render :json => {:success => :false , :errors => ['required fields are blank']}, status: 422
    end
  end

  api :GET, '/v1/b2b/users/', 'Fetch details of the current user'
  formats ['json']
  description <<-EOS
      == Long description
       Fetch the details of the current user
    EOS
  def show
    if current_user
      render :json => {:success => :true , :user => current_user.as_json(:methods => [:avatar_url])}
    else
      render :json => {:success => :false , :errors => ['You dont have user details']}
    end
  end

  def update
    if current_user.update(user_update_params)
      render :json => {:success => :true , :user =>  current_user.as_json(:methods => [:avatar_url])}
    else
      render :json => {:success => :false , :errors => current_user.errors.full_messages}, status: 422
    end
  end

  def change_password
    if params[:password] && params[:confirm_password] && params[:old_password]
      if params[:password] == params[:confirm_password]

        if current_user.password == Digest::SHA1.hexdigest(params[:old_password])
          current_user.updatePassword(params[:password])
          current_user.save
          render :json => {:success => :true , :user =>  current_user.as_json(:methods => [:avatar_url])}
        else
          render :json => {:success => :false , :errors => ["old password doesn't match"]}
        end
      else
        render :json => {:success => :false , :errors => ["password doesn't match"]}
      end
    else
      render :json => {:success => :false , :errors => ['field are blanks']}
    end
  end


  private
    def user_update_params
      params.permit(:name, :date_of_birth, :gender, :phone_no,:password, :avatar, :country_code, :organisation_name, :time_zone, :token)
    end

    def user_params
      params.permit(:name, :email, :date_of_birth, :gender, :phone_no,:password, :country_code, :organisation_name, :time_zone, :token)
    end
end

app/helpers/api/v1/admin/users_helper.rb
module Api::V1::Admin::UsersHelper
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/views/admin/users/_search.html.erb
<div class="col-lg-5">
  <%= form_tag '/admin/users', method: 'get', class: "sidebar-form" do %>
      <div class="input-group">
        <%= select_tag(:option, options_for_select(
        [ ['ID', 'id'],
          ['Name', 'name'],
          ['Email', 'email'],
          ['Organisation', 'org']
        ], selected: params[:option]
        ), class: "form-control", style: 'width: 40%;'
        ) %>
        <%= text_field_tag :q, params[:q], placeholder: "Search for a user", class: "form-control", style: 'width: 60%;' %>
        <div class="input-group-btn">
        <%= submit_tag "Search", :name => nil, class: "btn btn-flat", id: "search-btn"  %>
        </div>
      </div>
  <% end %>
</div>

app/views/admin/users/_tabs.html.erb
<ul class="nav nav-tabs" role="tablist">




  <li role="presentation" class="<%= controller.controller_name == 'users' && controller.action_name == 'index' && params[:keyword].blank? ? 'active': '' %>">

    <a href="<%= url_for :controller => 'users', :action => 'index' %>" aria-controls="verified" role="tab">Approved
      Users</a></li>


  <li role="presentation" class="<%= controller.controller_name == 'users' && controller.action_name == 'deactive' && params[:keyword].blank? ? 'active': '' %>">


    <a href="<%= url_for :controller => 'users', :action => 'deactive' %>" aria-controls="pending" role="tab">Deactivated
      Users</a></li>
</ul>

app/views/admin/users/deactive.html.erb
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-lg-1">
            <h4>Users</h4>
        </div>
          <%= render "search" %>
    </div>
    <br />

    <div>


        <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation">
        <a href="<%= url_for :controller => 'admin/users', :action => 'index' %>" aria-controls="verified" role="tab">Approved
          Users</a></li>
      <li role="presentation" class="active">
        <a href="<%= url_for :controller => 'admin/users', :action => 'deactive' %>" aria-controls="pending" role="tab">Deactivated
          Users</a></li>
    </ul>
    <br/>

    <!-- Tab panes -->
    <div class="tab-content content-bg">
      <div role="tabpanel" class="tab-pane active" id="verified">

        <!-- Tab panes -->

                                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th class="col-xs-1">User ID</th>
                        <th class="col-xs-2">Registered On</th>
                        <th class="col-xs-2">B2B Organisation</th>
                        <th class="col-xs-2">User Details</th>
                        <th class="col-xs-1">Prepaid credits</th>
                        <th class="col-xs-1">Status</th>
                        <th class="col-xs-1">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    <%
                       i = 0
                       styleClass = 'success'
                       @users.each do |user|
                         i =i+1

                         if i%2 == 0
                           styleClass = 'info'
                         end
                    %>
                        <tr class="info">
                            <td class="col-xs-1"><%= user.id %></td>
                            <td class="col-xs-2"><%= user.created_at.strftime("%d-%m-%Y %H:%M") %></td>
                            <td class="col-xs-1"><%= user.organisation_name %></td>
                            <td class="col-xs-2">
                                <%= user.name %> <br>
                                <%= user.email %><br>
                                <%= user.phone_no %>
                            </td>
                            <td class="col-xs-1"><%=  user.prepaid_credit_count ? user.prepaid_credit_count : '0' %></td>
                            <td class="col-xs-1"><%=  user.status ? 'Active' : 'Deactive' %> </td>
                            <td class="col-xs-2">
                                <a href="<%= url_for(edit_admin_user_path(user)) %>"><i class="glyphicon glyphicon-eye-open"></i>&nbsp; View</a>
                                &nbsp;
                            </td>
                        </tr>
                    <% end %>
                    </tbody>
                </table>
                <div class="pagination-wrapper">
                    <%= will_paginate @users %>
                </div>
            </div>
            <div role="tabpanel" class="tab-pane" id="pending">

            </div>
        </div>

    </div>
</section>

app/views/admin/users/edit.html.erb
<%= form_for @user, url: "#{admin_user_path}", :html => {:class => 'form'}  do |f| %>
    <%= render partial: "/shared/validation_errors", locals: { resource: @user } %>    <!-- Main content -->
    <section class="content">
        <div class="row">
            <section class="col-lg-12 connectedSortable">
                <!-- User Stats-->
                <div class="nav-tabs-custom">
                    <ul class="nav nav-tabs pull-right">
                        <li class="pull-left header"><i class="fa fa-user"></i> User Details</li>
                    </ul>
                    <br />

                        <div class="row">
                            <div class="col-lg-6 col-xs-12">
                                <div class="form-group">
                                    <label class="control-label col-lg-3 col-xs-12">User ID</label>

                                    <div class=" col-lg-7 col-xs-12">
                                        <label><%= @user.id %></label>
                                    </div>
                                </div>
                            </div><!-- ./col -->

                        </div><!-- /.row -->
                        <br />


                        <div class="row">
                            <div class="col-lg-6 col-xs-12">
                                <div class="form-group">
                                    <label class="control-label col-lg-3 col-xs-12">User Name</label>

                                    <div class=" col-lg-7 col-xs-12">
                                        <label><%= @user.name %></label>
                                    </div>
                                </div>
                            </div><!-- ./col -->

                            <div class="col-lg-6 col-xs-12">
                                <div class="form-group">
                                    <label class="control-label col-lg-3 col-xs-12">Organisation</label>

                                    <div class="col-lg-7 col-xs-12">
                                        <label><%= @user.organisation_name %></label>
                                    </div>
                                </div>
                            </div><!-- ./col -->
                        </div><!-- /.row -->
                        <br />




                        <div class="row">
                            <div class="col-lg-6 col-xs-12">
                                <div class="form-group">
                                    <label class="control-label col-lg-3 col-xs-12">Email</label>

                                    <div class="col-lg-7 col-xs-12">
                                        <label><%= @user.email %></label>
                                    </div>
                                </div>
                            </div><!-- ./col -->

                            <div class="col-lg-6 col-xs-12">
                                <div class="form-group">
                                    <label class="control-label col-lg-3 col-xs-12">Mobile Number</label>

                                    <div class="col-lg-7 col-xs-12">
                                        <label><%= @user.phone_no %></label>
                                    </div>
                                </div>
                            </div><!-- ./col -->
                        </div><!-- /.row -->
                        <br />

                        <div class="row">
                            <div class="col-lg-6 col-xs-12">
                                <div class="form-group">
                                    <label class="control-label col-lg-3 col-xs-12">Date of Birth</label>

                                    <div class="col-lg-7 col-xs-12">
                                        <label><%= @user.date_of_birth %></label>
                                    </div>
                                </div>
                            </div><!-- ./col -->

                            <div class="col-lg-6 col-xs-12">
                                <div class="form-group">
                                    <label class="control-label col-lg-3 col-xs-12">Gender</label>

                                    <div class="col-lg-7 col-xs-12">
                                        <label><%= @user.gender %></label>
                                    </div>
                                </div>
                            </div><!-- ./col -->
                        </div><!-- /.row -->
                        <br />

                        <div class="row">
                            <div class="col-lg-6 col-xs-12">
                                <div class="form-group">
                                    <label class="col-lg-3 col-xs-12">Prepaid Credits</label>

                                    <div class="col-lg-3 col-xs-4">
                                        <%= f.text_field :prepaid_credit_count, autofocus: true, class:'form-control'%>
                                    </div>
                                </div>
                            </div><!-- ./col -->
                        </div><!-- /.row -->
                        <br />

                        <div id="hidden-date-range" class="row">
                            <div class="col-lg-6 col-xs-12">
                                <div class="form-group">
                                    <label class="control-label col-lg-3 col-xs-12" for="reportfrom">From</label>

                                    <div class="col-lg-7 col-xs-12">
                                        <div class='input-group date'>
                                            <input id="reportfrom" type="text" class="form-control" data-provide="datepicker" placeholder="mm/dd/yyyy" />
                                                <span class="input-group-addon">
                                                    <span class="glyphicon glyphicon-calendar"></span>
                                                </span>
                                        </div>
                                    </div>
                                </div>
                            </div><!-- ./col -->

                            <div class="col-lg-6 col-xs-12">
                                <div class="form-group">
                                    <label class="control-label col-lg-3 col-xs-12" for="reportto">To</label>

                                    <div class="col-lg-7 col-xs-12">
                                        <div class='input-group date'>
                                            <input id="reportto" type="text" class="form-control" data-provide="datepicker" placeholder="mm/dd/yyyy" />
                                                <span class="input-group-addon">
                                                    <span class="glyphicon glyphicon-calendar"></span>
                                                </span>
                                        </div>
                                    </div>
                                </div>
                            </div><!-- ./col -->
                        </div>
                        <br />


                        <div class="row">
                            <div class="col-lg-6 col-xs-12">
                                <div class="form-group">
                                    <label class="control-label col-lg-3 col-xs-12" for="offrstat">Status</label>
                                    <div class=" col-lg-7 col-xs-12">
                                        Disable <%= f.check_box :status,  {}, false, true %>
                                    </div>
                                </div>
                            </div><!-- ./col -->
                        </div><!-- /.row -->
                </div>
            </section>
        </div><!-- /.row -->

        <div class="row">
            <div class="col-lg-2">
                <button id="addcreditok" type="submit" class="btn btn-primary btn-block">Update</button>
            </div>

            <div id="generate-report" class="col-lg-2">
                <button id="generatereport" type="button" class="btn btn-success btn-block" name="generate">Generate Report</button>
            </div>

            <div id="view-report" class="col-lg-2">
                <a onclick="generate()"> <button id="generatereport" type="button" class="btn btn-danger btn-block">View Report</button></a>
            </div>
        </div>
        <br />
    </section>
<% end %>
<script type="text/javascript" charset="utf - 8">
    /* after "$('a.back-to-top').hide();" */
	$('#hidden-date-range').hide();
	$('#view-report').hide();

    /* before "function onlyNumsAllowed(evt)" before the closing "});" */
	$('#generatereport').click(function() {
		$('#hidden-date-range').show();
		$('#view-report').show();
		$('#generate-report').hide();
	});
    function generate() {
        window.open(location.protocol + '//' + location.host + "<%= url_for :controller => 'users', :action => 'report' , :format => 'pdf', :id => @user.id  %>&to=" + $("#reportto").val() + "&from=" + $("#reportfrom").val());
    }
</script>

app/views/admin/users/index.html.erb
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-lg-1">
            <h4>Users</h4>
        </div>
        <%= render "search" %>
    </div>
    <br />

    <div>



      <%= render "tabs" %>


    <br/>

    <!-- Tab panes -->
    <div class="tab-content content-bg">
      <div role="tabpanel" class="tab-pane active" id="verified">

        <!-- Tab panes -->

                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th class="col-xs-1">User ID</th>
                        <th class="col-xs-2">Registered On</th>
                        <th class="col-xs-2">B2B Organisation</th>
                        <th class="col-xs-2">User Details</th>
                        <th class="col-xs-1">Prepaid credits</th>
                        <th class="col-xs-1">Status</th>
                        <th class="col-xs-1">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    <%
                       i = 0
                       styleClass = 'success'
                       @users.each do |user|
                         i =i+1

                         if i%2 == 0
                           styleClass = 'info'
                         end
                    %>
                        <tr class="info">
                            <td class="col-xs-1"><%= user.id %></td>
                            <td class="col-xs-2"><%= user.created_at.strftime("%d-%m-%Y %H:%M") %></td>
                            <td class="col-xs-1"><%= user.organisation_name %></td>
                            <td class="col-xs-2">
                                <%= user.name %> <br>
                                <%= user.email %><br>
                                <%= user.phone_no %>
                            </td>
                            <td class="col-xs-1"><%=  user.prepaid_credit_count ? user.prepaid_credit_count : '0' %></td>
                            <td class="col-xs-1"><%=  user.status ? 'Active' : 'Deactive' %> </td>
                            <td class="col-xs-1">
                                <a href="<%= url_for(edit_admin_user_path(user)) %>"><i class="glyphicon glyphicon-eye-open"></i>&nbsp; View</a>
                                &nbsp;
                            </td>
                        </tr>
                    <% end %>
                    </tbody>
                </table>
                <div class="pagination-wrapper">
                    <%= will_paginate @users %>
                </div>
            </div>
            <div role="tabpanel" class="tab-pane" id="pending">

            </div>
        </div>

    </div>
</section>

app/views/admin/users/show.html.erb
trest